{{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1" -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: tekton-operator-proxy-webhook
spec:
  selector:
    matchLabels:
      operator.tekton.dev/operand-name: tektoncd-pipelines
  portLevelMtls:
    443:
      mode: DISABLE
{{- end -}}