{{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1" -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: tekton-pipelines-webhook
spec:
  selector:
    matchLabels:
      app: tekton-pipelines-webhook
  portLevelMtls:
    443:
      mode: DISABLE
{{- end -}}