{{- if .Capabilities.APIVersions.Has "operator.tekton.dev/v1alpha1" -}}
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: {{ .profile }}
  targetNamespace: {{ .Release.Namespace | quote }}
  pipeline:
    options:
      deployments:
        tekton-pipelines-webhook:
          metadata:
            annotations:
              traffic.sidecar.istio.io/excludeOutboundPorts: "443"
              traffic.sidecar.istio.io/includeInboundPorts: "443"
  chain:
    options:
      deployments:
        tekton-triggers-webhook:
          metadata:
            annotations:
              traffic.sidecar.istio.io/excludeOutboundPorts: "443"
              traffic.sidecar.istio.io/includeInboundPorts: "443"
        tekton-triggers-core-interceptors:
          metadata:
            annotations:
              traffic.sidecar.istio.io/excludeOutboundPorts: "8443"
              traffic.sidecar.istio.io/includeInboundPorts: "8443"
  pruner:
    resources:
    - pipelinerun
    - taskrun
    keep: 100
    schedule: "0 8 * * *"
{{- end }}