{{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1" -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: tekton-triggers-webhook
spec:
  selector:
    matchLabels:
      app: tekton-triggers-webhook
  portLevelMtls:
    8443:
      mode: DISABLE
{{- end -}}